# QeMLflow API Stability & Versioning Configuration

# Version Management
version:
  # Version file location (relative to project root)
  file: "VERSION"
  
  # Default version if file doesn't exist
  default: "0.1.0"
  
  # Auto-bump settings
  auto_bump:
    enabled: true
    # Bump type based on commit messages
    commit_patterns:
      major: ["breaking", "!"]
      minor: ["feat", "feature"]
      patch: ["fix", "patch", "bug"]

# API Compatibility Testing
compatibility:
  # Enable API compatibility testing
  enabled: true
  
  # Snapshot settings
  snapshots:
    directory: "api_snapshots"
    retention_days: 365
    auto_create: true
    
  # Modules to analyze for API changes
  modules:
    - "src/qemlflow/**/*.py"
    
  # Breaking change detection
  breaking_changes:
    # Fail CI/CD on breaking changes
    fail_on_breaking: true
    # Exceptions (regex patterns for function/class names)
    exceptions:
      - "_.*"  # Private functions/classes
      - ".*_test.*"  # Test functions
      - ".*experimental.*"  # Experimental features

# Deprecation Policy
deprecation:
  # Enable deprecation management
  enabled: true
  
  # Deprecation tracking file
  file: "deprecations.json"
  
  # Warning settings
  warnings:
    # Frequency of warnings by deprecation level
    notice: "7d"      # Weekly
    scheduled: "1d"   # Daily
    pending: "1h"     # Hourly
    urgent: "1m"      # Every call
    
  # Auto-cleanup obsolete deprecations
  auto_cleanup: true
  
  # Deprecation timeline (versions)
  timeline:
    notice_to_scheduled: 2    # Minor versions
    scheduled_to_pending: 1   # Minor versions
    pending_to_removal: 1     # Major version

# Backward Compatibility Testing
backward_compatibility:
  # Enable backward compatibility testing
  enabled: true
  
  # Test settings
  tests:
    directory: "tests/compatibility"
    auto_discover: true
    
  # Compatibility matrix
  matrix:
    file: "compatibility_matrix.json"
    auto_update: true
    
  # Version range for testing
  test_versions:
    # Test against last N versions
    count: 5
    # Minimum version to test
    minimum: "1.0.0"

# CI/CD Integration
ci_cd:
  # Enable CI/CD workflows
  enabled: true
  
  # GitHub Actions workflows
  workflows:
    api_stability: true
    version_check: true
    deprecation_check: true
    compatibility_tests: true
    
  # Status checks
  required_checks:
    - "API Compatibility"
    - "Version Validation"
    - "Backward Compatibility"
    
  # Artifacts to preserve
  artifacts:
    - "api_snapshots/"
    - "compatibility_matrix.json"
    - "deprecations.json"
    - "docs/api/"

# Documentation
documentation:
  # Auto-generate API documentation
  auto_generate: true
  
  # Documentation output
  output:
    directory: "docs/api"
    format: ["json", "markdown"]
    
  # Include in documentation
  include:
    - version_info
    - deprecation_status
    - compatibility_matrix
    - migration_guides

# Notifications
notifications:
  # Enable notifications for API changes
  enabled: true
  
  # Notification channels
  channels:
    # Slack notifications (requires webhook URL)
    slack:
      enabled: false
      webhook_url: ""
      
    # Email notifications
    email:
      enabled: false
      recipients: []
      
    # GitHub issues
    github_issues:
      enabled: true
      # Create issues for breaking changes
      breaking_changes: true
      # Create issues for deprecation warnings
      deprecations: false

# Advanced Settings
advanced:
  # Parallel processing
  parallel:
    enabled: true
    workers: 4
    
  # Caching
  cache:
    enabled: true
    directory: ".qemlflow_cache"
    ttl: "24h"
    
  # Logging
  logging:
    level: "INFO"
    file: "logs/api_stability.log"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
