# QeMLflow Audit Trail System Configuration
# Enterprise-grade audit trail for compliance and reproducibility

# Storage Configuration
storage:
  # Base directory for audit logs
  base_dir: "audit_logs"
  
  # Storage backend options: local, database, cloud
  backend: "local"
  
  # Data retention policy
  retention:
    # Keep audit logs for 7 years (regulatory compliance)
    default_days: 2555  # 7 years
    # Archive after 1 year
    archive_after_days: 365
    # Compress archives after 30 days
    compress_after_days: 30
  
  # Compression settings
  compression:
    enabled: true
    algorithm: "gzip"  # gzip, bz2, lzma
    level: 6

# Logging Configuration
logging:
  # Logging levels
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  
  # Event types to log
  event_types:
    - "data_access"
    - "data_modification"
    - "computation"
    - "security"
    - "workflow"
    - "system"
  
  # Automatic event tracking
  auto_tracking:
    enabled: true
    function_calls: true
    data_operations: true
    file_operations: true
    system_events: true
  
  # Log format
  format:
    timestamp_format: "ISO8601"
    include_stack_trace: true
    include_system_metrics: true

# Data Lineage Configuration
data_lineage:
  # Enable data lineage tracking
  enabled: true
  
  # Tracking granularity
  granularity: "file"  # file, record, field
  
  # Checksum algorithm for data integrity
  checksum_algorithm: "sha256"
  
  # Maximum lineage depth to track
  max_lineage_depth: 20
  
  # Automatic lineage detection
  auto_detection:
    enabled: true
    file_operations: true
    database_operations: false  # Enable for database tracking
    api_calls: true
  
  # Lineage visualization
  visualization:
    enabled: true
    max_nodes: 1000
    layout: "hierarchical"  # hierarchical, force, circular

# Workflow Tracking Configuration
workflow_tracking:
  # Enable workflow tracking
  enabled: true
  
  # Automatic step detection
  auto_detection:
    enabled: true
    function_decorators: true
    context_managers: true
  
  # Performance metrics
  performance_tracking:
    cpu_usage: true
    memory_usage: true
    disk_io: true
    network_io: false
  
  # Dependency analysis
  dependency_analysis:
    enabled: true
    detect_circular: true
    optimize_execution: true

# Compliance Configuration
compliance:
  # Regulatory standards
  standards:
    - "GxP"      # Good Practice (FDA, EMA)
    - "21_CFR_11" # FDA 21 CFR Part 11
    - "GDPR"     # General Data Protection Regulation
    - "ISO_27001" # Information Security Management
    - "SOX"      # Sarbanes-Oxley Act
  
  # Data classification
  data_classification:
    enabled: true
    levels:
      - "public"
      - "internal"
      - "confidential"
      - "restricted"
    default_level: "internal"
  
  # Access control
  access_control:
    enabled: true
    authentication_required: true
    authorization_required: true
    role_based: true
  
  # Audit requirements
  audit_requirements:
    data_integrity: true
    user_authentication: true
    change_control: true
    electronic_signatures: false  # Enable for FDA validation
    time_stamping: true

# Security Configuration
security:
  # Encryption settings
  encryption:
    enabled: true
    algorithm: "AES-256"
    key_rotation_days: 90
  
  # Digital signatures
  digital_signatures:
    enabled: false  # Enable for high-security environments
    algorithm: "RSA-2048"
  
  # Integrity verification
  integrity:
    enabled: true
    checksum_verification: true
    tamper_detection: true
    blockchain_backup: false  # Enable for immutable audit trail
  
  # Access monitoring
  access_monitoring:
    failed_access_threshold: 5
    alert_on_suspicious_activity: true
    lockout_duration_minutes: 30

# Performance Configuration
performance:
  # Asynchronous processing
  async_processing:
    enabled: true
    batch_size: 100
    flush_interval_seconds: 60
  
  # Caching
  caching:
    enabled: true
    cache_size_mb: 100
    cache_ttl_seconds: 3600
  
  # Resource limits
  limits:
    max_memory_usage_mb: 500
    max_disk_usage_gb: 10
    max_file_size_mb: 100

# Reporting Configuration
reporting:
  # Automated reports
  automated_reports:
    enabled: true
    daily_summary: true
    weekly_compliance: true
    monthly_analytics: true
  
  # Report formats
  formats:
    - "json"
    - "csv"
    - "pdf"
    - "html"
  
  # Distribution
  distribution:
    email_reports: false
    dashboard_integration: true
    export_to_external: false
  
  # Custom reports
  custom_reports:
    enabled: true
    sql_queries: false  # Enable for custom SQL queries
    python_scripts: true

# Integration Configuration
integrations:
  # Experiment tracking integration
  experiment_tracking:
    enabled: true
    auto_link_experiments: true
    sync_parameters: true
  
  # Environment determinism integration
  environment_determinism:
    enabled: true
    auto_capture: true
    validate_reproducibility: true
  
  # External systems
  external_systems:
    siem_integration: false  # Security Information and Event Management
    log_aggregation: false   # ELK stack, Splunk, etc.
    alerting_systems: false  # PagerDuty, Slack, etc.

# Monitoring Configuration
monitoring:
  # Health checks
  health_checks:
    enabled: true
    interval_seconds: 300
    check_disk_space: true
    check_memory_usage: true
    check_log_rotation: true
  
  # Metrics collection
  metrics:
    enabled: true
    collection_interval_seconds: 60
    retention_days: 30
  
  # Alerting
  alerting:
    enabled: true
    thresholds:
      disk_usage_percent: 90
      memory_usage_percent: 85
      failed_events_per_hour: 10
      audit_lag_minutes: 30

# Development Configuration
development:
  # Debug mode
  debug: false
  
  # Testing mode
  testing_mode: false
  
  # Mock external dependencies
  mock_external: false
  
  # Sample data generation
  generate_sample_data: false

# Advanced Configuration
advanced:
  # Custom event processors
  custom_processors:
    enabled: false
    processor_modules: []
  
  # Plugin system
  plugins:
    enabled: false
    plugin_directories: []
  
  # API configuration
  api:
    enabled: false
    port: 8080
    authentication: "token"
  
  # Distributed processing
  distributed:
    enabled: false
    cluster_nodes: []
    replication_factor: 3
