# 🔒 QeMLflow Container Security Configuration
# Enterprise-grade security policies and hardening configurations

# =============================================================================
# CONTAINER SECURITY POLICIES
# =============================================================================

security:
  # Security scanning configuration
  scanning:
    enabled: true
    engines:
      - trivy
      - snyk
      - safety
      - bandit
    severity_threshold: "HIGH"
    fail_on_critical: true
    scan_frequency: "daily"
    
  # Runtime security policies
  runtime:
    non_root_user: true
    read_only_filesystem: true
    no_new_privileges: true
    drop_all_capabilities: true
    allowed_capabilities:
      - CAP_NET_BIND_SERVICE
    
  # Network security
  network:
    isolation: true
    internal_networks: true
    egress_filtering: true
    allowed_ports:
      production: [80, 443]
      development: [8000, 5000]
      jupyter: [8888]
      monitoring: [9090, 3000]
      
  # Resource security
  resources:
    memory_limits: true
    cpu_limits: true
    disk_quotas: true
    tmpfs_mounts: true
    
  # Secret management
  secrets:
    external_secrets: true
    no_env_secrets: true
    encrypted_storage: true
    rotation_enabled: true

# =============================================================================
# DOCKER SECURITY BASELINE
# =============================================================================

docker_security:
  # Base image security
  base_images:
    allowed_registries:
      - "python"
      - "gcr.io/distroless"
      - "docker.io/library"
    require_signature: true
    vulnerability_scan: true
    
  # Dockerfile best practices
  dockerfile:
    multi_stage: required
    non_root_user: required
    minimal_packages: required
    no_cache_layers: required
    explicit_tags: required
    
  # Container runtime security
  runtime_security:
    apparmor: enabled
    seccomp: enabled
    selinux: enabled
    user_namespaces: enabled
    
  # Image signing and verification
  content_trust:
    enabled: true
    notary_server: true
    delegation_keys: true

# =============================================================================
# KUBERNETES SECURITY POLICIES (Future)
# =============================================================================

kubernetes_security:
  # Pod Security Standards
  pod_security_standards:
    level: "restricted"
    enforce: true
    audit: true
    warn: true
    
  # Network Policies
  network_policies:
    default_deny: true
    ingress_rules: explicit
    egress_rules: explicit
    
  # RBAC Configuration
  rbac:
    least_privilege: true
    service_accounts: custom
    role_bindings: minimal
    
  # Admission Controllers
  admission_controllers:
    - PodSecurityPolicy
    - ResourceQuota
    - LimitRanger
    - SecurityContextDeny
    
  # Security Contexts
  security_contexts:
    run_as_non_root: true
    read_only_root_filesystem: true
    allow_privilege_escalation: false
    drop_capabilities: ["ALL"]

# =============================================================================
# SECURITY MONITORING & ALERTING
# =============================================================================

monitoring:
  # Container monitoring
  container_monitoring:
    runtime_security: true
    vulnerability_alerts: true
    anomaly_detection: true
    compliance_monitoring: true
    
  # Log monitoring
  log_monitoring:
    security_events: true
    access_logs: true
    error_tracking: true
    audit_trails: true
    
  # Metrics collection
  metrics:
    security_metrics: true
    performance_impact: true
    compliance_score: true
    threat_indicators: true

# =============================================================================
# COMPLIANCE FRAMEWORKS
# =============================================================================

compliance:
  # Industry standards
  standards:
    - "CIS Docker Benchmark"
    - "NIST Cybersecurity Framework"
    - "ISO 27001"
    - "SOC 2 Type II"
    
  # Regulatory compliance
  regulations:
    - "GDPR"
    - "HIPAA"
    - "SOX"
    
  # Security frameworks
  frameworks:
    - "OWASP Container Security"
    - "SANS Critical Controls"
    - "MITRE ATT&CK"

# =============================================================================
# INCIDENT RESPONSE
# =============================================================================

incident_response:
  # Automated response
  automation:
    container_isolation: true
    network_segmentation: true
    image_quarantine: true
    alert_escalation: true
    
  # Forensics preparation
  forensics:
    log_preservation: true
    image_snapshots: true
    network_captures: true
    memory_dumps: true
    
  # Recovery procedures
  recovery:
    backup_restoration: true
    clean_deployment: true
    security_validation: true
    post_incident_review: true
