# QeMLflow Experiment Tracking Configuration
# Enterprise-grade experiment tracking for scientific reproducibility

# Storage Configuration
storage:
  # Base directory for experiment storage
  base_dir: "experiments"
  
  # Storage backend options: local, s3, gcs, azure
  backend: "local"
  
  # Compression for experiment data
  compression:
    enabled: true
    algorithm: "gzip"  # gzip, bz2, lzma
    level: 6
  
  # Data retention policy
  retention:
    # Keep experiments for 1 year by default
    default_days: 365
    # Archive after 6 months
    archive_after_days: 180
    # Cleanup policy for failed experiments
    cleanup_failed_after_days: 30

# Experiment Metadata
metadata:
  # Automatic metadata capture
  auto_capture:
    system_info: true
    environment: true
    git_info: true
    hardware_info: true
    dependencies: true
  
  # Custom metadata fields
  custom_fields:
    - "project_name"
    - "researcher"
    - "hypothesis"
    - "methodology"
    - "expected_outcome"
  
  # Required fields for experiments
  required_fields:
    - "name"
    - "description"
    - "project_name"

# Parameter Tracking
parameters:
  # Automatic parameter detection
  auto_detect: true
  
  # Parameter validation
  validation:
    enabled: true
    strict_types: true
    range_checking: true
  
  # Parameter versioning
  versioning:
    enabled: true
    hash_based: true
    
  # Sensitive parameter handling
  sensitive_params:
    # Parameters to exclude from logs
    exclude:
      - "password"
      - "api_key"
      - "secret"
      - "token"
    # Parameters to hash instead of storing
    hash:
      - "email"
      - "username"

# Data Versioning
data_versioning:
  # Enable data versioning
  enabled: true
  
  # Hashing algorithm for data fingerprinting
  hash_algorithm: "sha256"
  
  # Track data changes
  track_changes: true
  
  # Data lineage tracking
  lineage:
    enabled: true
    max_depth: 10
    track_transformations: true
  
  # Large file handling
  large_files:
    threshold_mb: 100
    use_external_storage: true
    chunk_size_mb: 10

# Result Tracking
results:
  # Automatic result capture
  auto_capture:
    metrics: true
    plots: true
    models: true
    logs: true
  
  # Result validation
  validation:
    enabled: true
    tolerance: 1e-6
    statistical_tests: true
  
  # Result comparison
  comparison:
    enabled: true
    baseline_auto_select: true
    significance_level: 0.05
  
  # Result artifacts
  artifacts:
    # Automatically save model artifacts
    save_models: true
    # Automatically save plots
    save_plots: true
    # Compression for artifacts
    compress_artifacts: true

# Reproducibility Settings
reproducibility:
  # Seed management
  seed_management:
    enabled: true
    auto_set: true
    global_seed: 42
  
  # Environment capture
  environment_capture:
    enabled: true
    include_system: true
    include_python: true
    include_conda: true
    include_pip: true
  
  # Code versioning
  code_versioning:
    enabled: true
    auto_commit: false
    include_uncommitted: true
    hash_code: true

# Monitoring and Alerting
monitoring:
  # Performance monitoring
  performance:
    enabled: true
    track_memory: true
    track_cpu: true
    track_gpu: true
    track_disk: true
  
  # Progress tracking
  progress:
    enabled: true
    update_interval: 30  # seconds
    detailed_logging: true
  
  # Alerting
  alerts:
    enabled: false  # Enable for production
    # email: "alerts@company.com"
    # slack_webhook: "https://hooks.slack.com/..."
    thresholds:
      memory_usage_percent: 90
      disk_usage_percent: 85
      runtime_hours: 24

# Integration Settings
integrations:
  # MLflow integration
  mlflow:
    enabled: false
    tracking_uri: "http://localhost:5000"
  
  # Weights & Biases integration
  wandb:
    enabled: false
    project: "qemlflow"
  
  # TensorBoard integration
  tensorboard:
    enabled: true
    logdir: "logs/tensorboard"
  
  # Jupyter integration
  jupyter:
    enabled: true
    auto_capture_notebooks: true

# Security Settings
security:
  # Access control
  access_control:
    enabled: false  # Enable for multi-user environments
    authentication_required: false
  
  # Data encryption
  encryption:
    enabled: false  # Enable for sensitive data
    algorithm: "AES-256"
  
  # Audit logging
  audit:
    enabled: true
    log_file: "logs/experiment_audit.log"
    log_level: "INFO"

# Performance Settings
performance:
  # Parallel processing
  parallel:
    enabled: true
    max_workers: 4
  
  # Caching
  caching:
    enabled: true
    cache_dir: "cache"
    max_size_gb: 10
  
  # Batch processing
  batch:
    enabled: true
    batch_size: 100
    timeout_seconds: 300

# Development Settings
development:
  # Debug mode
  debug: false
  
  # Verbose logging
  verbose: true
  
  # Testing mode
  testing_mode: false
  
  # Auto-cleanup for development
  auto_cleanup: false
