# Automated Maintenance Configuration
# This file configures the automated maintenance system for QeMLflow

# Main configuration
enabled: true
check_interval_seconds: 300  # Check for scheduled tasks every 5 minutes
max_concurrent_tasks: 3
retention_days: 30

# Default executors to enable
default_executors:
  - dependency
  - security  
  - cleanup
  - scaling

# Task-specific configurations
task_defaults:
  dependency_update:
    schedule: weekly  # Run weekly dependency updates
    priority: medium
    enabled: true
    auto_approve_minor: true  # Auto-approve minor version updates
    auto_approve_patch: true  # Auto-approve patch version updates
    exclude_packages: []  # Packages to exclude from auto-updates
    
  security_patch:
    schedule: daily  # Check for security patches daily
    priority: high
    enabled: true
    auto_fix_high: true  # Auto-fix high severity vulnerabilities
    auto_fix_critical: true  # Auto-fix critical vulnerabilities
    notification_channels:
      - email
      - slack
    
  cleanup:
    schedule: daily  # Run cleanup daily
    priority: low
    enabled: true
    cleanup_patterns:
      - "__pycache__"
      - "*.pyc"
      - ".pytest_cache"
      - ".coverage"
      - "htmlcov"
      - ".mypy_cache"
      - "*.egg-info"
      - "build"
      - "dist"
      - ".tox"
    log_retention_days: 30
    temp_retention_days: 7
    
  scaling:
    schedule: "*/15 * * * *"  # Check every 15 minutes
    priority: medium
    enabled: true
    cpu_scale_threshold: 75.0  # Scale when CPU > 75%
    memory_scale_threshold: 80.0  # Scale when memory > 80%
    connection_scale_threshold: 1000  # Scale when connections > 1000
    scale_cooldown_minutes: 30  # Wait 30 minutes between scaling actions

# Notification settings
notifications:
  enabled: true
  channels:
    email:
      enabled: false
      smtp_server: ""
      smtp_port: 587
      username: ""
      password: ""
      to_addresses: []
    slack:
      enabled: false
      webhook_url: ""
      channel: "#maintenance"
    webhook:
      enabled: false
      url: ""
      headers: {}

# Monitoring integration
monitoring:
  enabled: true
  metrics_enabled: true
  health_checks_enabled: true
  
# Logging configuration  
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "maintenance.log"
  max_size_mb: 100
  backup_count: 5

# Security settings
security:
  require_approval_for_critical: true
  require_approval_for_major_updates: true
  audit_all_actions: true
  encrypted_storage: false
