# QeMLflow Performance Optimization Configuration
# Caching strategies, performance tuning, and optimization settings

performance:
  # Caching Configuration
  caching:
    enabled: true
    
    # Memory caching
    memory_cache:
      enabled: true
      max_size: "1GB"
      ttl: 3600  # seconds
      eviction_policy: "lru"  # lru, lfu, fifo
      
      # Cache categories
      categories:
        - name: "model_cache"
          max_size: "512MB"
          ttl: 7200
          priority: "high"
        - name: "data_cache"
          max_size: "256MB"
          ttl: 1800
          priority: "medium"
        - name: "result_cache"
          max_size: "256MB"
          ttl: 3600
          priority: "medium"
    
    # Distributed caching
    distributed_cache:
      enabled: false
      backend: "redis"  # redis, memcached
      servers:
        - "localhost:6379"
      cluster_mode: false
      replication: true
      
      # Redis-specific settings
      redis:
        db: 0
        password: null
        ssl: false
        connection_pool_size: 10
        socket_timeout: 5
        
    # File system caching
    file_cache:
      enabled: true
      cache_dir: "./cache"
      max_size: "2GB"
      cleanup_threshold: 0.8
      compression: true
      
      # Cache persistence
      persistence:
        enabled: true
        sync_interval: 300
        backup_enabled: true
        backup_interval: 3600
  
  # Performance Optimization Settings
  optimization:
    # CPU optimization
    cpu:
      enabled: true
      parallelization:
        enabled: true
        max_workers: "auto"  # auto, or specific number
        chunk_size: "auto"
        load_balancing: true
      
      # Computational optimization
      computation:
        vectorization: true
        jit_compilation: true
        loop_optimization: true
        memory_alignment: true
      
      # Threading
      threading:
        thread_pool_size: "auto"
        thread_affinity: false
        numa_awareness: true
    
    # Memory optimization
    memory:
      enabled: true
      
      # Memory management
      management:
        garbage_collection_tuning: true
        memory_pools: true
        buffer_optimization: true
        lazy_loading: true
      
      # Memory allocation
      allocation:
        pre_allocation: true
        memory_mapping: true
        huge_pages: false
        memory_compression: false
      
      # Limits and thresholds
      limits:
        max_memory_usage: "80%"
        gc_threshold: "70%"
        swap_threshold: "90%"
    
    # I/O optimization
    io:
      enabled: true
      
      # File I/O
      file_io:
        async_io: true
        buffer_size: "64KB"
        read_ahead: true
        write_behind: true
        direct_io: false
      
      # Network I/O
      network_io:
        connection_pooling: true
        keep_alive: true
        compression: true
        batching: true
        max_connections: 100
      
      # Database I/O
      database_io:
        connection_pooling: true
        prepared_statements: true
        batch_operations: true
        connection_timeout: 30
    
    # Algorithm optimization
    algorithms:
      enabled: true
      
      # Numerical algorithms
      numerical:
        blas_optimization: true
        lapack_optimization: true
        fft_optimization: true
        random_optimization: true
      
      # Machine learning algorithms
      ml_algorithms:
        model_quantization: false
        pruning: false
        distillation: false
        early_stopping: true
      
      # Data processing algorithms
      data_processing:
        streaming: true
        chunking: true
        indexing: true
        sorting_optimization: true

  # Performance Monitoring
  monitoring:
    enabled: true
    
    # Metrics collection
    metrics:
      collection_interval: 30
      retention_days: 7
      
      # Performance metrics
      performance_metrics:
        - "cpu_utilization"
        - "memory_utilization"
        - "disk_io_rate"
        - "network_io_rate"
        - "cache_hit_rate"
        - "response_time"
        - "throughput"
        - "error_rate"
      
      # Custom metrics
      custom_metrics:
        - name: "model_inference_time"
          type: "histogram"
          buckets: [0.1, 0.5, 1.0, 2.0, 5.0, 10.0]
        - name: "data_processing_rate"
          type: "gauge"
          unit: "items/second"
    
    # Performance thresholds
    thresholds:
      response_time:
        warning: 1000  # ms
        critical: 5000  # ms
      
      throughput:
        warning: 100   # requests/second
        critical: 50
      
      cache_hit_rate:
        warning: 0.8
        critical: 0.6
      
      error_rate:
        warning: 0.01
        critical: 0.05
    
    # Alerting
    alerts:
      - name: "high_response_time"
        condition: "response_time > 5000"
        duration: 300
        severity: "critical"
      
      - name: "low_cache_hit_rate"
        condition: "cache_hit_rate < 0.6"
        duration: 600
        severity: "warning"
      
      - name: "high_error_rate"
        condition: "error_rate > 0.05"
        duration: 180
        severity: "critical"

  # Performance Testing
  testing:
    enabled: true
    
    # Load testing
    load_testing:
      enabled: true
      scenarios:
        - name: "baseline_load"
          users: 10
          duration: "5m"
          ramp_up: "1m"
        
        - name: "peak_load"
          users: 100
          duration: "10m"
          ramp_up: "2m"
        
        - name: "stress_test"
          users: 500
          duration: "15m"
          ramp_up: "5m"
    
    # Performance benchmarks
    benchmarks:
      enabled: true
      
      # Baseline benchmarks
      baseline:
        model_inference: "100ms"
        data_processing: "1000 items/second"
        api_response: "500ms"
        memory_usage: "2GB"
      
      # Performance budgets
      budgets:
        page_load_time: "3s"
        api_response_time: "1s"
        model_inference_time: "200ms"
        memory_footprint: "4GB"
    
    # Regression testing
    regression_testing:
      enabled: true
      baseline_comparison: true
      threshold_deviation: 0.1  # 10%
      auto_regression_detection: true

# Environment-specific optimizations
environments:
  development:
    performance:
      caching:
        memory_cache:
          max_size: "256MB"
        file_cache:
          max_size: "512MB"
      optimization:
        cpu:
          parallelization:
            max_workers: 2
  
  staging:
    performance:
      caching:
        memory_cache:
          max_size: "512MB"
        file_cache:
          max_size: "1GB"
      optimization:
        cpu:
          parallelization:
            max_workers: 4
  
  production:
    performance:
      caching:
        memory_cache:
          max_size: "2GB"
        distributed_cache:
          enabled: true
        file_cache:
          max_size: "10GB"
      optimization:
        cpu:
          parallelization:
            max_workers: "auto"
        memory:
          allocation:
            huge_pages: true

# Profiling and Debugging
profiling:
  enabled: false  # Enable only when needed
  
  # CPU profiling
  cpu_profiling:
    enabled: false
    sampling_interval: 100  # microseconds
    stack_depth: 64
    
  # Memory profiling
  memory_profiling:
    enabled: false
    sampling_interval: 1000  # allocations
    track_allocations: true
    track_deallocations: true
  
  # I/O profiling
  io_profiling:
    enabled: false
    track_reads: true
    track_writes: true
    track_network: true
  
  # Output configuration
  output:
    format: "json"  # json, flamegraph, pprof
    output_dir: "./profiling_data"
    retention_days: 30
