# Production Configuration for QeMLflow
# This file contains production-specific settings optimized for performance, reliability, and security

production:
  # Environment settings
  environment: "production"
  debug: false
  log_level: "INFO"
  
  # Performance optimization
  performance:
    # Memory management
    memory:
      # Maximum memory per process (in MB)
      max_memory_per_process: 4096
      # Memory threshold for garbage collection
      gc_threshold: 0.8
      # Enable memory monitoring
      enable_monitoring: true
      # Memory leak detection threshold
      leak_detection_threshold: 0.95
    
    # CPU optimization
    cpu:
      # Maximum CPU usage percentage
      max_cpu_usage: 0.85
      # Number of worker processes (auto-detect if null)
      worker_processes: null
      # Enable CPU affinity
      enable_affinity: true
      # CPU throttling threshold
      throttling_threshold: 0.9
    
    # I/O optimization
    io:
      # Maximum concurrent I/O operations
      max_concurrent_io: 100
      # I/O buffer size (in KB)
      buffer_size: 64
      # Enable async I/O
      enable_async: true
      # I/O timeout (in seconds)
      timeout: 30
    
    # Network optimization
    network:
      # Connection pool size
      connection_pool_size: 50
      # Connection timeout (in seconds)
      connection_timeout: 10
      # Read timeout (in seconds)
      read_timeout: 30
      # Keep-alive timeout (in seconds)
      keep_alive_timeout: 60
      # Enable compression
      enable_compression: true
    
    # Database optimization
    database:
      # Connection pool settings
      pool_size: 20
      max_overflow: 30
      pool_timeout: 30
      pool_recycle: 3600
      # Query optimization
      query_timeout: 60
      # Enable query caching
      enable_query_cache: true
      # Cache size (number of entries)
      cache_size: 1000
    
    # Caching configuration
    caching:
      # Enable distributed caching
      distributed: true
      # Cache expiration (in seconds)
      expiration: 3600
      # Maximum cache size (in MB)
      max_size: 1024
      # Cache eviction policy
      eviction_policy: "lru"
      # Enable cache compression
      enable_compression: true
    
    # Resource limits
    limits:
      # Maximum file size for uploads (in MB)
      max_file_size: 1024
      # Maximum request size (in MB)
      max_request_size: 100
      # Rate limiting (requests per minute)
      rate_limit: 1000
      # Maximum concurrent requests
      max_concurrent_requests: 200

  # Reliability settings
  reliability:
    # Health check configuration
    health_checks:
      enabled: true
      interval: 30  # seconds
      timeout: 10   # seconds
      failure_threshold: 3
      success_threshold: 1
    
    # Circuit breaker configuration
    circuit_breaker:
      enabled: true
      failure_threshold: 5
      recovery_timeout: 60  # seconds
      half_open_max_calls: 3
    
    # Retry configuration
    retry:
      max_attempts: 3
      backoff_factor: 2.0
      max_delay: 60  # seconds
      jitter: true
    
    # Timeout configuration
    timeouts:
      api_request: 30       # seconds
      database_query: 60    # seconds
      file_operation: 300   # seconds
      computation: 3600     # seconds

  # Security hardening
  security:
    # Enable all security features
    enable_authentication: true
    enable_ssl: true
    enable_monitoring: true
    enable_audit_logging: true
    
    # Session management
    session:
      timeout: 3600         # seconds
      secure_cookies: true
      httponly_cookies: true
      samesite: "strict"
    
    # API security
    api:
      enable_cors: false
      allowed_origins: []
      enable_csrf_protection: true
      max_request_size: 100  # MB
    
    # Data protection
    data:
      enable_encryption_at_rest: true
      enable_encryption_in_transit: true
      backup_encryption: true
      audit_data_access: true

  # Monitoring and observability
  monitoring:
    # Metrics collection
    metrics:
      enabled: true
      interval: 15          # seconds
      retention: 2592000    # 30 days in seconds
      export_format: "prometheus"
    
    # Logging configuration
    logging:
      level: "INFO"
      format: "structured"
      enable_correlation_ids: true
      enable_sensitive_data_masking: true
      retention_days: 90
      max_file_size: 100    # MB
      max_files: 10
    
    # Alerting configuration
    alerting:
      enabled: true
      channels: ["email", "slack"]
      thresholds:
        cpu_usage: 0.8
        memory_usage: 0.8
        disk_usage: 0.85
        error_rate: 0.05
        response_time: 2.0    # seconds
    
    # Profiling (disabled in production by default)
    profiling:
      enabled: false
      sampling_rate: 0.001
      memory_profiling: false

  # Deployment configuration
  deployment:
    # Scaling configuration
    scaling:
      min_replicas: 2
      max_replicas: 10
      target_cpu_utilization: 70
      target_memory_utilization: 75
      scale_up_stabilization: 60   # seconds
      scale_down_stabilization: 300 # seconds
    
    # Rolling update configuration
    rolling_update:
      max_surge: 1
      max_unavailable: 0
      progress_deadline: 600  # seconds
    
    # Resource requests and limits
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2000m"
        memory: "4Gi"
    
    # Startup and liveness probes
    probes:
      startup:
        initial_delay: 30
        period: 10
        timeout: 5
        failure_threshold: 30
      liveness:
        initial_delay: 30
        period: 10
        timeout: 5
        failure_threshold: 3
      readiness:
        initial_delay: 5
        period: 5
        timeout: 3
        failure_threshold: 3

  # Backup and disaster recovery
  backup:
    enabled: true
    schedule: "0 2 * * *"  # Daily at 2 AM
    retention_days: 30
    compression: true
    encryption: true
    verify_integrity: true
    
    # Disaster recovery
    disaster_recovery:
      enabled: true
      replication_mode: "async"
      failover_timeout: 300  # seconds
      automatic_failover: true
      backup_frequency: "daily"

  # Maintenance configuration
  maintenance:
    # Automated maintenance windows
    maintenance_window:
      enabled: true
      start_time: "02:00"
      duration: 120  # minutes
      timezone: "UTC"
      days: ["sunday"]
    
    # Update policies
    updates:
      security_updates: "automatic"
      dependency_updates: "scheduled"
      system_updates: "manual"
    
    # Cleanup policies
    cleanup:
      log_retention: 90      # days
      temp_file_cleanup: 24  # hours
      cache_cleanup: 7       # days
      audit_log_retention: 365  # days
