# QeMLflow Validation Framework Configuration
# Comprehensive validation infrastructure for scientific reproducibility

# Storage Configuration
storage:
  # Base directory for validation results
  results_dir: "validation_results"
  
  # Subdirectories for different result types
  subdirs:
    validation: "validations"
    benchmarks: "benchmarks"
    reports: "reports"
    statistics: "statistics"
  
  # File formats
  formats:
    results: "json"  # json, pickle, csv
    reports: "json"  # json, html, pdf
    logs: "jsonl"

# Cross-Validation Configuration
cross_validation:
  # Default cross-validation settings
  default_folds: 5
  default_method: "kfold"  # kfold, stratified, timeseries
  
  # Available methods and their configurations
  methods:
    kfold:
      shuffle: true
      random_state: 42
    
    stratified:
      shuffle: true
      random_state: 42
    
    timeseries:
      max_train_size: null
      test_size: null
  
  # Scoring metrics
  scoring:
    classification:
      - "accuracy"
      - "precision_macro"
      - "recall_macro"
      - "f1_macro"
      - "roc_auc_ovr"
    
    regression:
      - "neg_mean_squared_error"
      - "neg_mean_absolute_error"
      - "r2"
      - "neg_root_mean_squared_error"
  
  # Performance thresholds
  thresholds:
    min_accuracy: 0.6
    max_std_dev: 0.2
    min_samples: 100

# Benchmark Testing Configuration
benchmark:
  # Standard datasets for benchmarking
  datasets:
    classification:
      - name: "iris"
        source: "sklearn"
        target_accuracy: 0.95
      - name: "wine"
        source: "sklearn"
        target_accuracy: 0.90
      - name: "breast_cancer"
        source: "sklearn"
        target_accuracy: 0.92
    
    regression:
      - name: "boston"
        source: "sklearn"
        target_r2: 0.70
      - name: "diabetes"
        source: "sklearn"
        target_r2: 0.45
  
  # Baseline models for comparison
  baselines:
    classification:
      - name: "random_forest"
        params:
          n_estimators: 100
          random_state: 42
      - name: "logistic_regression"
        params:
          random_state: 42
    
    regression:
      - name: "random_forest"
        params:
          n_estimators: 100
          random_state: 42
      - name: "linear_regression"
        params: {}
  
  # Performance targets
  targets:
    accuracy_threshold: 0.8
    r2_threshold: 0.6
    training_time_limit: 300  # seconds
    inference_time_limit: 1   # seconds

# Statistical Validation Configuration
statistical:
  # Statistical tests to perform
  tests:
    normality:
      - "shapiro_wilk"
      - "kolmogorov_smirnov"
    
    comparison:
      - "t_test"
      - "mann_whitney"
      - "wilcoxon"
    
    correlation:
      - "pearson"
      - "spearman"
  
  # Significance levels
  significance_levels:
    alpha: 0.05
    bonferroni_correction: true
  
  # Sample size requirements
  sample_sizes:
    min_size: 30
    power: 0.8
    effect_size: 0.5

# Continuous Validation Configuration
continuous:
  # Scheduling
  schedule:
    enabled: false
    interval: 3600  # seconds (1 hour)
    max_concurrent: 3
  
  # Triggers
  triggers:
    - type: "data_change"
      threshold: 0.1  # 10% change
    - type: "model_update"
      immediate: true
    - type: "performance_degradation"
      threshold: 0.05  # 5% degradation
  
  # Notifications
  notifications:
    enabled: true
    channels:
      - "email"
      - "slack"
    thresholds:
      critical: 0.1
      warning: 0.05

# Reporting Configuration
reporting:
  # Report generation
  auto_generate: true
  formats:
    - "json"
    - "html"
  
  # Report content
  include:
    summary_statistics: true
    detailed_metrics: true
    visualizations: true
    recommendations: true
    reproducibility_info: true
  
  # Visualization settings
  visualizations:
    enabled: true
    formats:
      - "png"
      - "svg"
    dpi: 300
    
    plots:
      - "score_distribution"
      - "learning_curves"
      - "confusion_matrix"
      - "roc_curves"
  
  # Quality assessment
  quality_metrics:
    consistency_threshold: 0.1
    reliability_threshold: 0.8
    performance_threshold: 0.7

# Integration Configuration
integration:
  # Experiment tracking integration
  experiment_tracking:
    enabled: true
    auto_log: true
    
  # Audit trail integration
  audit_trail:
    enabled: true
    log_all_validations: true
    
  # Environment determinism integration
  environment:
    enabled: true
    capture_environment: true

# Performance Configuration
performance:
  # Parallel execution
  parallel:
    enabled: true
    max_workers: 4
    
  # Memory management
  memory:
    max_memory_gb: 8
    cleanup_after_validation: true
    
  # Caching
  caching:
    enabled: true
    cache_dir: ".validation_cache"
    ttl: 86400  # 24 hours

# Security Configuration
security:
  # Data privacy
  privacy:
    anonymize_sensitive_data: true
    encrypt_results: false
    
  # Access control
  access:
    require_authentication: false
    allowed_users: []
    
  # Audit logging
  audit:
    log_access: true
    log_modifications: true

# Compliance Configuration
compliance:
  # Regulatory requirements
  regulations:
    fda_21_cfr_part_11: false
    gxp_compliance: false
    
  # Documentation requirements
  documentation:
    validation_protocols: true
    traceability_matrix: true
    change_control: true
    
  # Validation levels
  levels:
    analytical: true
    operational: true
    performance: true

# Logging Configuration
logging:
  # Log levels
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  
  # Log formats
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Log destinations
  handlers:
    - type: "file"
      filename: "validation.log"
      max_size: "10MB"
      backup_count: 5
    - type: "console"
      level: "INFO"

# Feature Flags
features:
  # Experimental features
  experimental:
    automated_hyperparameter_tuning: false
    advanced_statistical_tests: false
    deep_learning_validation: false
    
  # Beta features
  beta:
    real_time_validation: false
    distributed_validation: false
    
  # Deprecated features
  deprecated:
    legacy_api: false
