# 🏭 Production Environment Configuration  
# Enterprise-grade production settings

application:
  debug: false
  log_level: "INFO"

security:
  authentication:
    enabled: true
    token_expiry: 1800  # 30 minutes
  
  authorization:
    rbac_enabled: true
    default_role: "readonly"
  
  encryption:
    data_at_rest: true
    data_in_transit: true
  
  session:
    secure_cookies: true
    max_age: 1800

database:
  url: "postgresql://qemlflow:${DB_PASSWORD}@${DB_HOST}:5432/qemlflow_prod"
  echo: false
  pool_size: 20
  max_overflow: 10
  pool_timeout: 30
  connect_args:
    sslmode: "require"
    application_name: "qemlflow-production"

performance:
  workers: 4
  max_connections: 1000
  timeout: 30
  
  cache:
    enabled: true
    backend: "redis"
    ttl: 3600
    max_size: "1GB"
  
  optimizations:
    lazy_loading: true
    connection_pooling: true
    query_caching: true
    static_file_caching: true

monitoring:
  metrics:
    enabled: true
    port: 8080
  
  health_checks:
    enabled: true
    interval: 15
    timeout: 5
  
  logging:
    format: "json"
    level: "INFO"
    rotation: "daily"
    max_size: "500MB"
    retention_days: 30

resources:
  memory:
    limit: "4GB"
    warning_threshold: 0.85
  
  cpu:
    limit: "4.0"
    warning_threshold: 0.85
  
  disk:
    limit: "50GB"
    warning_threshold: 0.90

scientific:
  experiment_tracking:
    enabled: true
    backend: "mlflow"
    auto_log: true
  
  model_optimization:
    parallel_training: true
    gpu_acceleration: true
    memory_optimization: true

external_services:
  redis:
    url: "redis://${REDIS_HOST}:6379/0"
    pool_size: 20
    timeout: 5
  
  message_queue:
    backend: "celery"
    broker_url: "redis://${REDIS_HOST}:6379/1"
    result_backend: "redis://${REDIS_HOST}:6379/2"

features:
  advanced_analytics: true

# Production-specific settings
production:
  high_availability: true
  auto_scaling: true
  comprehensive_monitoring: true
  security_hardened: true
  performance_optimized: true
