# 🏭 QeMLflow Production Configuration
# Enterprise-grade production settings for optimal performance and security

# =============================================================================
# APPLICATION CONFIGURATION
# =============================================================================
application:
  name: "QeMLflow Enterprise Platform"
  version: "1.0.0"
  environment: "production"
  debug: false
  log_level: "INFO"
  
# =============================================================================
# SECURITY CONFIGURATION
# =============================================================================
security:
  authentication:
    enabled: true
    method: "oauth2"
    token_expiry: 3600
  
  authorization:
    rbac_enabled: true
    default_role: "user"
    admin_users: []
  
  encryption:
    data_at_rest: true
    data_in_transit: true
    algorithm: "AES-256-GCM"
  
  session:
    secure_cookies: true
    same_site: "strict"
    max_age: 3600

# =============================================================================
# PERFORMANCE CONFIGURATION
# =============================================================================
performance:
  workers: 4
  max_connections: 1000
  timeout: 30
  keep_alive: 2
  
  cache:
    enabled: true
    ttl: 3600
    max_size: "1GB"
  
  database:
    pool_size: 20
    max_overflow: 10
    pool_timeout: 30

# =============================================================================
# MONITORING CONFIGURATION
# =============================================================================
monitoring:
  metrics:
    enabled: true
    port: 8080
    path: "/metrics"
  
  health_checks:
    enabled: true
    interval: 30
    timeout: 10
  
  logging:
    format: "json"
    level: "INFO"
    rotation: "daily"
    max_size: "100MB"

# =============================================================================
# RESOURCE LIMITS
# =============================================================================
resources:
  memory:
    limit: "2GB"
    warning_threshold: 0.8
  
  cpu:
    limit: "2.0"
    warning_threshold: 0.8
  
  disk:
    limit: "10GB"
    warning_threshold: 0.9
