name: Security Check

"on":
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit
    
    - name: Check dependencies for vulnerabilities
      run: |
        pip install -r requirements-core.txt
        safety check || echo "Safety check completed with warnings"
    
    - name: Run bandit security linter
      run: |
        bandit -r src/ -f json -o security-report.json || echo "Bandit completed with warnings"
        bandit -r src/ || echo "Bandit scan completed"
